exports.guildChoices = [
  { name: 'Ahch-To (ACT)', value: 'Ahch-To' },
  { name: 'Alderaan (ALD)', value: 'Alderaan' },
  { name: 'Bespin (BPN)', value: 'Bespin' },
  { name: 'Concord Dawn (CCD)', value: 'Concord Dawn' },
  { name: 'Coruscant (COR)', value: 'Coruscant' },
  { name: 'Dagobah (DGB)', value: 'Dagobah' },
  { name: 'Endor (FOE)', value: 'Endor' },
  { name: 'Exegol (EXG)', value: 'Exegol' },
  { name: 'Geonosis (GEO)', value: 'Geonosis' },
  { name: 'Hoth (HTH)', value: 'Hoth' },
  { name: 'Ilum (ILM)', value: 'Ilum' },
  { name: 'Jedha (JDH)', value: 'Jedha' },
  { name: 'Kamino (KMO)', value: 'Kamino' },
  { name: 'Kashyyyk (KAS)', value: 'Kashyyyk' },
  { name: 'Korriban (KOR)', value: 'Korriban' },
  { name: 'Lothal (LOT)', value: 'Lothal' },
  { name: 'Mandalore (MDL)', value: 'Mandalore' },
  { name: 'Mortis (MTS)', value: 'Mortis' },
  { name: 'Mustafar (MF)', value: 'Mustafar' },
  { name: 'Naboo (NBO)', value: 'Naboo' },
  { name: 'Nar Shaddaa (NAR)', value: 'Nar Shaddaa' },
  { name: 'Ryloth (RYL)', value: 'Ryloth' },
  { name: 'Scarif (SCF)', value: 'Scarif' },
  { name: 'Tatooine (TAT)', value: 'Tatooine' },
];
